In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('StudentPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1 Adding a new column

## 1.1 assign()

##### When to use assign?
##### > Add multiple columns in a single line of code
##### > When you need to overwrite the values of existing columns (best practice)
##### 
##### It returns a new object (a copy) with all the original columns in addition to the new ones

In [6]:
import numpy as np

In [7]:
# create random numbers for our new score columns
score1 = np.random.randint(1, 100, size=7)
score2 = np.random.randint(1, 100, size=7)

In [13]:
print("score1: ", score1)
print("score2: ", score2)

score1:  [57 76 70 22 92 80 84]
score2:  [70 52  7 62  3 83 62]

In [8]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0,7))
series2 = pd.Series(score2, index=np.arange(0,7))

In [14]:
print("Series1: ", series1)
print("Series2: ", series2)

Series1:  0    57
1    76
2    70
3    22
4    92
5    80
6    84
dtype: int32
Series2:  0    70
1    52
2     7
3    62
4     3
5    83
6    62
dtype: int32

In [15]:
# using assign() to add multiple columns (Note this is only a copy)
df_exams.assign(score1 = series1, score2 = series2)

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,score1,score2
0,female,group B,bachelor,standard,none,72,72,74,57,70
1,female,group C,some college,standard,completed,69,90,88,76,52
2,female,group B,master,standard,none,90,95,93,70,7
3,male,group A,associate,free/reduced,none,47,57,44,22,62
4,male,group C,some college,standard,none,76,78,75,92,3
5,female,group B,associate,standard,none,71,83,78,80,83
6,female,group B,some college,standard,none,88,95,92,84,62

In [18]:
# to change the original dataframe, since assign only creates a copy
df_exams = df_exams.assign(score1 = series1, score2 = series2)
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,score1,score2
0,female,group B,bachelor,standard,none,72,72,74,57,70
1,female,group C,some college,standard,completed,69,90,88,76,52
2,female,group B,master,standard,none,90,95,93,70,7
3,male,group A,associate,free/reduced,none,47,57,44,22,62
4,male,group C,some college,standard,none,76,78,75,92,3
5,female,group B,associate,standard,none,71,83,78,80,83
6,female,group B,some college,standard,none,88,95,92,84,62

# 1.2 insert()

#### inserts a new column at a specific position or index.

In [22]:
# using index() to add a column at a specific position. 
# Note insert method does not return a copy, it overwirtes the dataframe
# insert(index number, 'name', value)
df_exams.insert(1, 'test', series1)

ValueError: cannot insert test, already exists

In [23]:
# show dataframe
df_exams

,gender,test,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,score1,score2
0,female,57,group B,bachelor,standard,none,72,72,74,57,70
1,female,76,group C,some college,standard,completed,69,90,88,76,52
2,female,70,group B,master,standard,none,90,95,93,70,7
3,male,22,group A,associate,free/reduced,none,47,57,44,22,62
4,male,92,group C,some college,standard,none,76,78,75,92,3
5,female,80,group B,associate,standard,none,71,83,78,80,83
6,female,84,group B,some college,standard,none,88,95,92,84,62