In [2]:
import pandas as pd

In [4]:
df_laptops = pd.read_csv('laptop_price.csv')

In [6]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# 1 Create a column based on 1 condition np.where()

In [8]:
import numpy as np

In [13]:
# create an array based on price tiers
# np.where(condition, condition is true, condition is false)
np.where(df_laptops['Price_euros'] > 2000,
         'Expensive', 'Cheap')

array(['Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap', 'Cheap',
       'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Expensive', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Expensive', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap', 'Cheap',
       'Cheap', 'Cheap', 'Cheap', 'Cheap'], dtype='<U9')

In [14]:
# set it to a new column
df_laptops['Price_tier'] = np.where(df_laptops['Price_euros'] > 2000,
         'Expensive', 'Cheap')

In [15]:
# show first 5 rows
df_laptops.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap

In [16]:
# count values in price_tier column
df_laptops.value_counts('Price_tier')

Price_tier
Cheap        94
Expensive     5
Name: count, dtype: int64

## 1.1 Exercise

In [22]:
# create an array based on screen size (screen size > 15)
np.where(df_laptops['Inches'] > 15,
         'Large', 'Medium/Small')

array(['Medium/Small', 'Medium/Small', 'Large', 'Large', 'Medium/Small',
       'Large', 'Large', 'Medium/Small', 'Medium/Small', 'Medium/Small',
       'Large', 'Large', 'Large', 'Large', 'Medium/Small', 'Medium/Small',
       'Large', 'Large', 'Large', 'Medium/Small', 'Medium/Small', 'Large',
       'Large', 'Medium/Small', 'Large', 'Large', 'Medium/Small', 'Large',
       'Large', 'Large', 'Large', 'Medium/Small', 'Large', 'Medium/Small',
       'Medium/Small', 'Medium/Small', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Medium/Small',
       'Large', 'Large', 'Large', 'Large', 'Medium/Small', 'Large',
       'Large', 'Medium/Small', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Medium/Small', 'Medium/Small',
       'Medium/Small', 'Large', 'Large', 'Large', 'Medium/Small', 'Large',
       'Large', 'Medium/Small', 'Medium/Small', 'Large', 'Large',
       'Medium/Small', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Medium/Small', 'Medium/Small', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Medium/Small', 'Large', 'Large',
       'Medium/Small', 'Large', 'Medium/Small', 'Medium/Small', 'Large',
       'Large', 'Large'], dtype='<U12')

In [26]:
# set it to a new column
df_laptops['Screen_Size'] = np.where(df_laptops['Inches'] > 15,
         'Large', 'Medium/Small')

In [24]:
# show first 5 rows
df_laptops.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Screen Size
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap,Medium/Small
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,Medium/Small
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,Large
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Large
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap,Medium/Small

In [27]:
# count values in screen_size column
df_laptops.value_counts('Screen_Size')

Screen_Size
Large           67
Medium/Small    32
Name: count, dtype: int64