In [5]:
import pandas as pd

In [7]:
df_laptops = pd.read_csv('laptop_price.csv')

In [9]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# 1 drop_duplicated()

In [14]:
# drop duplicates in 2 or more columns
df_laptops.drop_duplicates(['Company'])[['Company', 'Price_euros']].value_counts()

Company    Price_euros
Acer       400.00         1
Apple      1339.69        1
Asus       1495.00        1
Chuwi      244.99         1
Dell       498.90         1
HP         575.00         1
Lenovo     499.00         1
MSI        2449.00        1
Microsoft  1089.00        1
Name: count, dtype: int64

In [18]:
# sort dataframe ascending by company and price
# cheapest first and most expensive last
df_laptops = df_laptops.sort_values(['Company','Price_euros'])

In [26]:
# cheapest keep='first'
df_laptops.drop_duplicates(['Company'])[['Company','Price_euros']]

      Company  Price_euros
95       Acer       847.00
17      Apple      2858.00
65       Asus      1983.00
30      Chuwi       244.99
33       Dell      1869.00
92         HP      1197.00
21     Lenovo       999.00
58        MSI      2449.00
70  Microsoft      1089.00

In [29]:
# most expensive keep='last'
# save changes to dataframe inplace=True
df_laptops.drop_duplicates(['Company'], keep='last', inplace=True, ignore_index=True)

In [31]:
# Arguments

# inplace: drop duplicates in place or return a copy.
# ignore_index=True: the resulting axis will be labeled 0,1,...
df_laptops[['Company', 'Price_euros']]

     Company  Price_euros
0       Acer       847.00
1      Apple      2858.00
2       Asus      1983.00
3      Chuwi       244.99
4       Dell      1869.00
5         HP      1197.00
6     Lenovo       999.00
7        MSI      2449.00
8  Microsoft      1089.00

# 2 Exercise 1

Task: Find the biggest and smallest screen size in laptops of each company using the sort_values() 
and duplicated() methods (keep "first", "last", and False

In [38]:
# Sort dataframe ascending by company and inches
# smallest first and biggest last
df_laptops = df_laptops.sort_values(['Company','Inches'])

In [42]:
# smallest: keep='first'
df_laptops.drop_duplicates(['Company'])[['Company','Inches']]

     Company  Inches
0       Acer    13.3
1      Apple    15.4
2       Asus    15.6
3      Chuwi    15.6
4       Dell    13.3
5         HP    13.3
6     Lenovo    15.6
7        MSI    17.3
8  Microsoft    13.5

In [40]:
#biggest: keep='last'
df_laptops.drop_duplicates(['Company'], keep='last')[['Company','Inches']]

     Company  Inches
0       Acer    13.3
1      Apple    15.4
2       Asus    15.6
3      Chuwi    15.6
4       Dell    13.3
5         HP    13.3
6     Lenovo    15.6
7        MSI    17.3
8  Microsoft    13.5