In [2]:
import pandas as pd

In [4]:
df_laptops = pd.read_csv('laptop_price.csv')

In [6]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# 1 Filter dataframe bases on 1 condition

In [8]:
# find Apple laptops
df_laptops['Company'] == 'Apple'

0      True
1      True
2     False
3      True
4      True
      ...
94    False
95    False
96    False
97    False
98    False
Name: Company, Length: 99, dtype: bool

In [10]:
# find laptops that cost more than 2000 euros
df_laptops['Price_euros']>2000

0     False
1     False
2     False
3      True
4     False
      ...
94    False
95    False
96    False
97    False
98    False
Name: Price_euros, Length: 99, dtype: bool

# 2 Filter dataframe based on multiple conditions

In [13]:
# find Apple laptops that cost more than 2000 euros
(df_laptops['Company'] == 'Apple') & (df_laptops['Price_euros']>2000)

0     False
1     False
2     False
3      True
4     False
      ...
94    False
95    False
96    False
97    False
98    False
Length: 99, dtype: bool

## 2.1 & (and operator)

In [14]:
# filter dataframe based on multiple conditions
df_laptops[(df_laptops['Company'] == 'Apple') & (df_laptops['Price_euros']>2000)]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
12,13,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.8GHz,16GB,256GB SSD,AMD Radeon Pro 555,macOS,1.83kg,2439.97
17,18,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.9GHz,16GB,512GB SSD,AMD Radeon Pro 560,macOS,1.83kg,2858.00

## 2.2 | (or operator)

In [16]:
# find laptops Apple or Dell
(df_laptops['Company'] == 'Apple') | (df_laptops['Company'] == 'Dell')

0      True
1      True
2     False
3      True
4      True
      ...
94    False
95    False
96     True
97     True
98    False
Name: Company, Length: 99, dtype: bool

In [22]:
# filter dataframe based on multiple conditions
df_laptops[(df_laptops['Company'] == 'Apple') | (df_laptops['Company'] == 'Dell')].value_counts('Company')

Company
Dell     24
Apple    14
Name: count, dtype: int64

In [24]:
# find laptops from Apple or Dell that cost over 2000 euros
((df_laptops['Company'] == 'Apple') | (df_laptops['Company'] == 'Dell')) & (df_laptops['Price_euros']>2000)

0     False
1     False
2     False
3      True
4     False
      ...
94    False
95    False
96    False
97    False
98    False
Length: 99, dtype: bool

In [25]:
df_laptops[((df_laptops['Company'] == 'Apple') | (df_laptops['Company'] == 'Dell')) & (df_laptops['Price_euros']>2000)]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
12,13,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.8GHz,16GB,256GB SSD,AMD Radeon Pro 555,macOS,1.83kg,2439.97
17,18,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.9GHz,16GB,512GB SSD,AMD Radeon Pro 560,macOS,1.83kg,2858.00