In [ ]:
# you can create dataframes with 2D arrays or 
# dictionaries or CSV files

In [2]:
import pandas as pd
import numpy as np

# 1 Creating a dataframe from an array

## 1.1 Option 1

In [3]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [4]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
            columns=['col1','col2'])

In [5]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [6]:
# creating an array with list shape
data = [[1,4], [2,5], [3,6]]

In [7]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
            columns=['col1','col2'])

In [8]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# 2 Creating a dataframe from an dictionary

In [9]:
# lists used for this example
states = ['CA', 'TX', 'FL', 'NY']
population = [300000, 290000, 260000, 190000]

In [10]:
# storing lists within a distionary
dict_states = {'States':states, 'Population':population}

In [11]:
# creating the dataframe
df_population = pd.DataFrame(dict_states)

In [12]:
# showing the dataframe
df_population

  States  Population
0     CA      300000
1     TX      290000
2     FL      260000
3     NY      190000

# 3 Creating a dataframe from a CSV file

In [16]:
# reading the csv file
df_exams = pd.read_csv('StudentPerformance.csv')
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

In [17]:
# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [18]:
# show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

In [20]:
# show last n rows in a dataframe
df_exams.head(10)

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

In [21]:
df_exams.tail(10)

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

In [22]:
# getting access to the shape attribute
df_exams.shape
# (rows, col)

(7, 8)

In [25]:
# display n rows (all n rows)
pd.set_option('display.max_rows',7)
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92