In [ ]:
''' 
Attributes - values associated w/ an object.
Referenced by name using dotted expressions
    example: 
        df.columns
'''

In [ ]:
''' 
Functions - a group of related statements that performs a
            specific task.
    example: 
        max()
        min()
        len()
'''

In [ ]:
''' 
Methods - functions which are defined inside a class body.
    example: 
        df.head()
        # head() belongs in DataFrame class
'''

In [1]:
import pandas as pd

In [5]:
# reading the csv file by using the .read_csv() method
df_exams = pd.read_csv('StudentPerformance.csv')

In [4]:
# showing the dataframe
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

# 1 Attributes

In [7]:
# getting access to the shape attribute
df_exams.shape

(7, 8)

In [8]:
# getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=7, step=1)

In [10]:
# getting access to the column attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental leave ', 'lunch',
       'test preparation', 'math score', 'reading score', 'writing score'],
      dtype='object')

In [14]:
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

In [13]:
# data types of each column
df_exams.dtypes

gender              object
race/ethnicity      object
parental leave      object
lunch               object
test preparation    object
math score           int64
reading score        int64
writing score        int64
dtype: object

# 2 Methods

In [16]:
# showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [17]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7 non-null      object
 1   race/ethnicity    7 non-null      object
 2   parental leave    7 non-null      object
 3   lunch             7 non-null      object
 4   test preparation  7 non-null      object
 5   math score        7 non-null      int64
 6   reading score     7 non-null      int64
 7   writing score     7 non-null      int64
dtypes: int64(3), object(5)
memory usage: 580.0+ bytes

In [19]:
# describing basic statistics of the dataframe
df_exams.describe()
# count is how many rows
# mean, sum of the data divided by the total rows (7)
# std, standard deviation
# min, minimum value
# max, max value
# 25%, Q1 percentile
# 50%, Q2
# 75%, Q3

       math score  reading score  writing score
count    7.000000       7.000000       7.000000
mean    73.285714      81.428571      77.714286
std     14.256160      13.794409      16.839579
min     47.000000      57.000000      44.000000
25%     70.000000      75.000000      74.500000
50%     72.000000      83.000000      78.000000
75%     82.000000      92.500000      90.000000
max     90.000000      95.000000      93.000000

# 3 Functions

In [27]:
# obtaining the length of the dataframe (number of rows)
len(df_exams)

7

In [28]:
# obtaining the highest index of the dataframe (rows - 1)
max(df_exams.index)

6

In [29]:
# obtaining the lowest index of the dataframe 
min(df_exams.index)

0

In [32]:
# obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [34]:
# rounding the values of the dataset
round(df_exams, 2)
# the 2 is rounding the decimal point to 2 places

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92