In [3]:
import pandas as pd

In [5]:
# read csv
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select columns
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality',	'club']]

In [7]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# 1 Selecting with a single value

loc[row_label, column_label]

In [9]:
# get all data about L.Messi
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [11]:
# get height of L.Messi
df.loc['L. Messi', 'height_cm']

170

In [12]:
#get weight of Christiano Ronaldo
df.loc['Cristiano Ronaldo', 'weight_kg']

83

In [16]:
# get all rows inside the 'height_cm' column
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [19]:
# get all columns that correspond to the index 'L. Messi'
df.loc['L. Messi',:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

# 2 Selecting with a list of values

In [23]:
# get all data about 'L. Messi' and 'Cristiano Ronaldo'
df.loc[['L. Messi','Cristiano Ronaldo'],:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [24]:
# get the height of 'L. Messi' and 'Cristiano Ronaldo'
df.loc[['L. Messi','Cristiano Ronaldo'],'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [25]:
# get height and weight of 'L. Messi'
df.loc['L. Messi',['height_cm','weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [26]:
# get height and weight of 'L. Messi' and 'Cristiano Ronaldo'
df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm','weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

# 3 Selecting a range of data with a slice

start:stop:step

Note: contrary to usual python slices, both the start and the stop are included

In [30]:
# slice column labels
players = ['L. Messi','Cristiano Ronaldo']
df.loc[players,'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [32]:
# slice index labels
columns = ['age','dob','height_cm','weight_kg']

# get top1 and top10 player names
#df.index[:10]

df.loc[['L. Messi', 'M. Salah' ],columns]

            age         dob  height_cm  weight_kg
short_name
L. Messi     32  1987-06-24        170         72
M. Salah     27  1992-06-15        175         71

# 4 Selecting with conditions

In [38]:
# one condition: select player with height above 180cm
columns = ['age','dob','height_cm','weight_kg']

df.loc[df['height_cm']>180, columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [40]:
# multiple conditions: select player with height above 180cm from Argentina

df.loc[(df['height_cm']>180) & (df['nationality']=='Argentina'), :]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors