In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('StudentPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1 Selecting 2 or more columns

In [4]:
# selecting 2 columns using [[]]
df_exams[['gender', 'math score']]

   gender  math score
0  female          72
1  female          69
2  female          90
3    male          47
4    male          76
5  female          71
6  female          88

In [5]:
# check out the data type of the selection
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [9]:
# select 2 or more columns using [[]]
df_exams[['gender','math score', 'reading score','writing score']]
# Note: 1 pair of [] is a series (array)
#       2 pair of [[]] is a DataFrame

   gender  math score  reading score  writing score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75
5  female          71             83             78
6  female          88             95             92

In [10]:
# we can't select 2 or more columns with .
df_exams.'gender', 'math score'

SyntaxError: invalid syntax (3466398017.py, line 2)