In [2]:
import pandas as pd

In [4]:
# read csv
df_exams = pd.read_csv("StudentPerformance.csv")
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

# 1 Create Index

In [7]:
import numpy as np
import random

In [13]:
# creating non repetitive values for the index
new_index = np.arange(0,7)

In [14]:
# shuffling the indexes
random.shuffle(new_index)

In [15]:
# create a new column with new index
df_exams['new_index'] = new_index

In [16]:
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,new_index
0,female,group B,bachelor,standard,none,72,72,74,2
1,female,group C,some college,standard,completed,69,90,88,4
2,female,group B,master,standard,none,90,95,93,1
3,male,group A,associate,free/reduced,none,47,57,44,0
4,male,group C,some college,standard,none,76,78,75,6
5,female,group B,associate,standard,none,71,83,78,5
6,female,group B,some college,standard,none,88,95,92,3

# 2 Set Index

In [35]:
# set new_index column as index
# Note inplace argument dictates whether dataframe is updated, True means update
df_exams.set_index('new_index', inplace=True)
df_exams

KeyError: "None of ['new_index'] are in the columns"

# 3 Sort Index

In [30]:
# sort dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
new_index,,,,,,,,
0,male,group A,associate,free/reduced,none,47,57,44
1,female,group B,master,standard,none,90,95,93
2,female,group B,bachelor,standard,none,72,72,74
3,female,group B,some college,standard,none,88,95,92
4,female,group C,some college,standard,completed,69,90,88
5,female,group B,associate,standard,none,71,83,78
6,male,group C,some college,standard,none,76,78,75

In [31]:
# sort descending by index
df_exams.sort_index(ascending=False, inplace=True)

In [32]:
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
new_index,,,,,,,,
6,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
4,female,group C,some college,standard,completed,69,90,88
3,female,group B,some college,standard,none,88,95,92
2,female,group B,bachelor,standard,none,72,72,74
1,female,group B,master,standard,none,90,95,93
0,male,group A,associate,free/reduced,none,47,57,44