In [2]:
import pandas as pd

In [4]:
# read csv
df_exams = pd.read_csv('StudentPerformance.csv')
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

# Sort a DataFrame

In [7]:
# sort by one column
df_exams.sort_values('math score')

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
3,male,group A,associate,free/reduced,none,47,57,44
1,female,group C,some college,standard,completed,69,90,88
5,female,group B,associate,standard,none,71,83,78
0,female,group B,bachelor,standard,none,72,72,74
4,male,group C,some college,standard,none,76,78,75
6,female,group B,some college,standard,none,88,95,92
2,female,group B,master,standard,none,90,95,93

In [8]:
# sort descending by one column
df_exams.sort_values('math score', ascending=False)

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
2,female,group B,master,standard,none,90,95,93
6,female,group B,some college,standard,none,88,95,92
4,male,group C,some college,standard,none,76,78,75
0,female,group B,bachelor,standard,none,72,72,74
5,female,group B,associate,standard,none,71,83,78
1,female,group C,some college,standard,completed,69,90,88
3,male,group A,associate,free/reduced,none,47,57,44

In [16]:
# sort descending by multiple columns
df_exams.sort_values(['math score','reading score'], ascending=False)

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
2,female,group B,master,standard,none,90,95,93
6,female,group B,some college,standard,none,88,95,92
4,male,group C,some college,standard,none,76,78,75
0,female,group B,bachelor,standard,none,72,72,74
5,female,group B,associate,standard,none,71,83,78
1,female,group C,some college,standard,completed,69,90,88
3,male,group A,associate,free/reduced,none,47,57,44

In [15]:
# Note: the sort_values only creats a copy, doesn't update orignial dataframe
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate,standard,none,71,83,78
6,female,group B,some college,standard,none,88,95,92

In [21]:
# sort descending by multiple columns and update dataframe
df_exams.sort_values(['math score','reading score'], ascending=False, inplace=True)

In [22]:
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
2,female,group B,master,standard,none,90,95,93
6,female,group B,some college,standard,none,88,95,92
4,male,group C,some college,standard,none,76,78,75
0,female,group B,bachelor,standard,none,72,72,74
5,female,group B,associate,standard,none,71,83,78
1,female,group C,some college,standard,completed,69,90,88
3,male,group A,associate,free/reduced,none,47,57,44

In [23]:
# sort descending with a key function
df_exams.sort_values('race/ethnicity', ascending=True)

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
3,male,group A,associate,free/reduced,none,47,57,44
2,female,group B,master,standard,none,90,95,93
6,female,group B,some college,standard,none,88,95,92
0,female,group B,bachelor,standard,none,72,72,74
5,female,group B,associate,standard,none,71,83,78
4,male,group C,some college,standard,none,76,78,75
1,female,group C,some college,standard,completed,69,90,88

In [24]:
# or another way
df_exams.sort_values('race/ethnicity', ascending=True, key=lambda col:col.str.lower())

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
3,male,group A,associate,free/reduced,none,47,57,44
2,female,group B,master,standard,none,90,95,93
6,female,group B,some college,standard,none,88,95,92
0,female,group B,bachelor,standard,none,72,72,74
5,female,group B,associate,standard,none,71,83,78
4,male,group C,some college,standard,none,76,78,75
1,female,group C,some college,standard,completed,69,90,88